import os, csv

PATHS = ['Site Summary 100418 v4.csv','autogenerated_summary.csv']

def get_root():
	past_root = os.getcwd()
	os.chdir('../CSVs')
	root = os.getcwd()+'/'
	os.chdir(past_root)
	return root

def read(path, offset):
	with open(path, newline='') as file:
		for i in range(offset):
			file.readline()
		reader = csv.reader(file, delimiter=',', quotechar='\"')
		return [row[0] for row in reader if row[0]]

def get_sites():
	temp = []
	offset = (2,0)
	for i in range(len(PATHS)):
		temp.append(read(PATHS[i], offset[i]))
	return temp

def find_missing(sites):
	map = {t:None for t in sites[0]}
	for t in sites[1]:
		if t not in map:
			print(t)

if __name__ == '__main__':
	ROOT = get_root()
	PATHS = [ROOT+path for path in PATHS]
	sites = get_sites()
	find_missing(sites)
